### ISSUE TITLE
Is the most_picked branch supposed to have information already filled in for words.json and words_picked.json, or should it have the empty {}?

### ISSUE THREAD

**Issue by ghost** [wlauyeung/Skribblio-Bot#1]
The `main` branch contains the empty object `{}` for `unsorted_words.json`.

**Comment by wlauyeung** [comment]
`words.json` should have the full sorted word list in the language that is being run on saved before the bot runs. This is because the bot also participates in guessing in order to expedite the game. It uses the same algorithm as the chrome extension so you can reuse existing word banks. For other languages that are not already supported by the chrome extension, you can just leave it empty or fish the word list out using the main branch bot. Note that if you do decide to use an empty word list, the bot will not attempt to guess thus increasing round time. 

`words_picked.json` is the data collected by the bot. If you are running the bot with the same language it ran last time then the file should not be empty. Conversely, the file should be empty since they are using completely different word lists.

**Comment by ghost** [comment]
Didn't realize you labelled and pinned it lol (also as I was writing this I noticed you [mentioned this issue](https://github.com/wlauyeung/Skribblio-Bot/blob/most_picked/README.md), as well as modifying the `config.json` file and blanking out the object in the `words_picked.json` file). I know you've mentioned before that the [other languages don't usually have games](https://github.com/wlauyeung/Skribblio-Word-Bank/issues/1#issuecomment-1594233218) (especially nowadays as probably fewer people are playing with the reporting options in the new update and the game is dying down), but assuming that there is a game in another language, you're saying that if I use the same file across multiple languages, the data will get messed up because it won't accurately reflect the skribbl.io players in the original language during the time that the bot is running, especially with multiple languages having some of the same words like `Abraham Lincoln`?

**Comment by wlauyeung** [comment]
>  you're saying that if I use the same file across multiple languages, the data will get messed up because it won't accurately reflect the skribbl.io players in the original language during the time that the bot is running, especially with multiple languages having some of the same words like `Abraham Lincoln`?

Yes, I have no clue whether all shared words have the same meaning across different languages. Like apple could mean something entirely different in another language thus should not share the same difficulty. Moreover, I am assuming you will eventually try to merge the data into their corresponding word bank and it will be inefficient when you try do to that. Although the word lists themselves are pretty small, it's something to take note of.

**Comment by ghost** [comment]
It is generally not possible to separate merged word difficulty data before inputting it into the correct language's word bank. That problem can be easily prevented by separating identical, similar, and different words into the languages that they were originally recorded in from the start, while making the code compatible with all of them (which it already is). For context, the Node.js installer gives me the option to install Python, so I accepted. Due to this, I'm not running the script right now because I was on the wrong version of Python (I was unaware that there was a new version) when I checked all the install options and the latest version of the PowerShell part of the Node.js installation process for Windows did not show how much percentage was being installed, so I closed the task, repaired my Python installation, and then modified it to add the rest of the installation options after finishing the previous step. I am not trying to merge word difficulty data, and even if I did, I wouldn't want it to be in the word bank files because it would be inaccurate, as I already understand why this wouldn't make sense from your response.

I don't take any responsibility for the following situation, and I don't think you will either, but despite the warning, it's very possible that someone who finds this repository and goes to the `most_picked` branch may accidentally use the English `words.json` file despite intentionally changing the language in `config.json`. Maybe you could link to where the other word lists are? You might've realized that the code won't work unless either it's edited or the file gets renamed to just `words.json` and is also put in the correct directory, though, so feel free to explain that.
